### ISSUE TITLE
Banners are pitch black upon relogging to the server.

### ISSUE THREAD

**Issue by WoophRadu** [MylesIsCool/ViaVersion#486]
### What version of ViaVersion are you using? Type /ver viaversion
0.9.8
### What version of Spigot are you using? Type /ver
git-Spigot-e4d4710-e1ebe52 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
### What plugins are you using? Type /plugins
https://i.gyazo.com/a76c97b585919df0f0724fb1d7d02cd3.png
### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
No.
### How does this error happen? login? Using an item? 
Almost all banners are black upon relogging. If placing a banner, it will retain it's colors until relogging to the server. I'm using client version 1.10.2 with OptiFine (HD C2 patch) and no other mods.
### Is there an error in the console? Use pastebin.com. Is there a kick message?
There's nothing in the console related to this.

I can provide any additional info. Thanks :)

**Comment by Matsv** [comment]
Can't reproduce this.

Could you try using normal Minecraft without mods?

**Comment by WoophRadu** [comment]
Yeah I tried. And I managed to reproduce it. But it's not like what I initially explained.
If you place some banners in chunk A and some in chunk B and you delog in chunk A, the banners in chunk A will keep their colors, but those in chunk B (and most of other chunks) are all black. (I tested in multiple locations around my world, same result)

**Comment by Matsv** [comment]
Could you use this (http://myles.us/ViaVersion/BKCommonLib.jar) build of bkcommonlib or try to remove it completely? I'm pretty sure it's caused by that, same issue occurred with signs at the time. That build should fix it.

**Comment by WoophRadu** [comment]
I was always using that build of BKCommonLib, because that's what you said on the Spigot page. I redownloaded that jar just to make sure, still was able to reproduce it. Removed it, still reproduced. Happened with signs too from what I'm remembering, didn't test yet.

**Comment by Matsv** [comment]
Could you try to debug it? Remove some plugins and see which one is causing it?

**Comment by WoophRadu** [comment]
Yup, found it with my first guess. It's Skyoseasons. Basically, this is a seasons plugin that hooks into ProtocolLib and changes the chunks' biomes to certain config-set biomes, but just for the player (the world doesn't actually get modified). This happens at evey season-change, but also at **server startup**, which is where I'm guessing the confilct comes from. If you guys can do nothing about it, then I apologize for bothering. It's certainly Skyoseasons' fault, it also bugs my entities sometimes to the point that they're all invisible... It's such a messy plugin.

**Comment by Matsv** [comment]
That plugin doesn't register the chunk packets listener as async, this will probably cause the problem (also did with BKCommonLib). Link: https://github.com/Skyost/Skyoseasons/blob/master/src/fr/skyost/seasons/utils/packets/Listener3.java
