### ISSUE TITLE
Players Randomly Get Kicked

### ISSUE THREAD

**Issue by JabEraMC** [MylesIsCool/ViaVersion#651]
### What is the output link of /viaversion dump? 
https://gist.github.com/anonymous/bfcdbfc0cdc0e854ebc4122fcd59f7ab

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
Bungeecord - Newest Build #1229

Plugins - http://imgur.com/a/GHpYW (One Server)

### How does this error happen? login? Using an item? 
Completely Random. It can happen to the same person 4 times an hour or 1 time a day. It can also either kick all players or one at a time.

### Is there an error in the console? Use pastebin.com. Is there a kick message?
None that I could find. With ViaVersion Debug enabled or just regular logs.

Additional Information: This happens on all of my servers with ViaVersion installed. Even my hubs. That's what leads me to believe it is ViaVersion.

**Comment by JabEraMC** [comment]
UPDATE - I looked at my bungee console waiting to get kicked - Heres the error I got when I got kicked. https://pastebin.com/eXJpDcDB

**Comment by MylesIsCool** [comment]
Disable /viaversion autoteam and this should fix it.

**Comment by JabEraMC** [comment]
Can confirm this did not fix it. I've also tried it on a server with just the latest version of Essentials, HoloDisplays, and ViaVersion, and Pex. Still happens. Still on bungee though. Could it be Bungee causing it?

**Comment by MylesIsCool** [comment]
You need to disable autoteam on all your servers. You can do this by config too.
