### ISSUE TITLE
Scoreboard (color) problems.

### ISSUE THREAD

**Issue by TheIntelloBox** [MylesIsCool/ViaVersion#878]
Using ViaVersion 1.4.0.

In 1.13: http://image.noelshack.com/fichiers/2018/29/4/1531995400-probleme-viaversion.jpg
In 1.12: http://www.noelshack.com/2018-29-4-1531996666-probleme-viaversion-2.jpg

**Comment by Gerrygames** [comment]
https://github.com/MylesIsCool/ViaVersion/issues/859

**Comment by MylesIsCool** [comment]
Could you confirm if this is fixed in our latest build?

https://ci.viaversion.com/job/ViaVersion/

If no, just say we'll reopen the issue. Also confirm what scenarios this issue occurs in, eg. only sidebar.

**Comment by TheIntelloBox** [comment]
Not fixed

**Comment by KennyTV** [comment]
Are you sure you updated correctly? The missing colors have disappeared both in the scoreboard and the player tags in every case for us

**Comment by TheIntelloBox** [comment]
Not me. :/

**Comment by TheIntelloBox** [comment]
http://image.noelshack.com/fichiers/2018/31/1/1532939772-scoreboard.jpg

**Comment by TheIntelloBox** [comment]
# Should we use prefix for team colour on 1.13 and above clients
team-colour-fix: true

**Comment by MylesIsCool** [comment]
Could you try this version by creeper?

https://cdn.discordapp.com/attachments/410074908811329536/474285765682266121/ViaVersion-1.4.2-SNAPSHOT.jar

**Comment by toxamin** [comment]
i dont see the problem here, just put the color code again...

**Comment by MylesIsCool** [comment]
Should be fixed in latest build on https://ci.viaversion.com/job/ViaVersion/

**Comment by TheMonDon** [comment]
Sorry to re-open this, but i'm still having this issue.

**Comment by TheMonDon** [comment]
> Should be fixed in latest build on https://ci.viaversion.com/job/ViaVersion/

I'm still having this issue in version 2.0.0 with 1.12.2 server and 1.13/1.14 client

**Comment by krusic22** [comment]
Can you provide screenshot? Also latest version is 2.0.1.

**Comment by MylesIsCool** [comment]
Use #1255 for this
